### ISSUE TITLE
Question about scroll down chat conversation at first chat page load

### ISSUE THREAD

**Issue by elvismdev** [royboy789/wordpress-firebase-chat#6]
I have a doubt/question about the function call `$scope.scrollChat();` at [line 15 of js/chatroom_app.js](https://github.com/royboy789/wordpress-firebase-chat/blob/master/js/chatroom_app.js#L15) When the first chat room page load happens and the chat is already full with earlier messages, this call to `$scope.scrollChat();` at line 15 shouldn't load the chat scrolled all the way to the bottom so I can see the newest messages? Actually it does it when I send a new message to the chat room, which is fine, but when I first get into the chat room page the chat room is loaded but with the scroll to the top showing me the beginning of the chat.

Just wondering if this is the purpose of `$scope.scrollChat();` at line 15 or if there is a bug or is something missing that could be affecting that functionality. Or if it's me who might be missing something else LOL.

**Comment by royboy789** [comment]
it should scroll you to the bottom of the chat window so you see the latest messages

**Comment by elvismdev** [comment]
That's what I'm expecting, but it only does it when I submit a new message, not when I come into (load) the chat page by the first time. [I see in your chat demo](http://roysivan.com/angularjs-for-wordpress/chat-rooms/roys-awesome-chat-room/), this happens also, when I get to the page for the first time I have to manually scroll down first to see the latest messages. If I just type a new message it will scroll down to the bottom as expected, but it would be good to have the chat load/render already with the scroll on the bottom showing the latest messages in first place. See for example [the chat at the right of a LIVE streaming at Youtube](https://www.youtube.com/watch?v=sw4hmqVPe0E). This is exactly what I'm trying to replicate for a live webcasts platform I'm working on.

**Comment by royboy789** [comment]
I'll have to look at it, maybe it is loading that function before all the chat messages load in

**Comment by elvismdev** [comment]
Yeah that's what I'm guessing. I'll try to look tonight around that point also.

**Comment by elvismdev** [comment]
Just sent this approach https://github.com/royboy789/wordpress-firebase-chat/pull/7 which fixed this issue in my case. Definitely `$scope.scrollChat();` is loading before all the chat messages loads in.
