### ISSUE TITLE
Error: undefined is not an object (evaluating '$scope.fireChat.chat') angular.min.js:102

### ISSUE THREAD

**Issue by ApacheWebServices** [royboy789/wordpress-firebase-chat#8]
Hello there,
Thank you for the firebase based chat plugin. I was wondering if the plugin needs upgrade....I am getting the following error as I try to chat. Also it does not post anything to firebase.

https://domainname.com/wp-json/wp/v2/chatrooms/30-----404

Error: undefined is not an object (evaluating '$scope.fireChat.chat') angular.min.js:102
newChat@https://domainname.com/wp-content/plugins/chat-rooms-powered-by-firebase/js/chatroom_app.js?ver=3.0:35:23
https://domainname.com/wp-content/plugins/angularjs-for-wp/js/angular.min.js:198:117
f@https://domainname.com/wp-content/plugins/angularjs-for-wp/js/angular.min.js:227:196
$eval@https://domainname.com/wp-content/plugins/angularjs-for-wp/js/angular.min.js:125:120
$apply@https://domainname.com/wp-content/plugins/angularjs-for-wp/js/angular.min.js:125:340
https://domainname.com/wp-content/plugins/angularjs-for-wp/js/angular.min.js:227:253
dispatch@https://domainname.com/wp-includes/js/jquery/jquery.js?ver=1.11.3:4:8554
handle@https://domainname.com/wp-includes/js/jquery/jquery.js?ver=1.11.3:4:5257

**Comment by royboy789** [comment]
I just cloned my repo into a fresh WP install and it worked fine.. did you remember to add in your firebase URL into the settings?
